language: generic 
sudo: required
services:
    - docker

before-install:
    - docker build -t madhan46/docker-react -f Dockerfile.dev .   
    
script:
    - docker run -e CI=true madhan46/docker-react npm run test -- --coverage 